// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonAPI.Data;

#nullable disable

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20260806144117_AddUniqueNames")]
    partial class AddUniqueNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokemonAPI.Models.MiPokemon", b =>
                {
                    b.Property<int>("MiPokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MiPokemonId"));

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("NombrePersonalizado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("SaludActual")
                        .HasColumnType("int");

                    b.HasKey("MiPokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("MisPokemons", t =>
                        {
                            t.HasCheckConstraint("CK_MiPokemon_Nivel", "[Nivel] >= 1 AND [Nivel] <= 100");

                            t.HasCheckConstraint("CK_MiPokemon_SaludActual", "[SaludActual] >= 0");
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.MiPokemonMovimiento", b =>
                {
                    b.Property<int>("MiPokemonId")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("int");

                    b.HasKey("MiPokemonId", "Slot");

                    b.HasIndex("MovimientoId");

                    b.HasIndex("MiPokemonId", "MovimientoId")
                        .IsUnique();

                    b.ToTable("MiPokemonMovimientos", t =>
                        {
                            t.HasCheckConstraint("CK_MiPokemonMovimiento_Slot", "[Slot] >= 1 AND [Slot] <= 4");
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.Movimiento", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Poder")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("MovimientoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Movimientos", t =>
                        {
                            t.HasCheckConstraint("CK_Movimiento_Categoria", "[Categoria] IN (0,1,2)");

                            t.HasCheckConstraint("CK_Movimiento_Poder_Segun_Categoria", "([Categoria] = 2 AND [Poder] = 0) OR ([Categoria] IN (0,1) AND [Poder] > 0)");
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.Pokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PokemonId"));

                    b.Property<int>("AtaqueBase")
                        .HasColumnType("int");

                    b.Property<int>("AtaqueEspecialBase")
                        .HasColumnType("int");

                    b.Property<int>("DefensaBase")
                        .HasColumnType("int");

                    b.Property<int>("DefensaEspecialBase")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SaludTotalBase")
                        .HasColumnType("int");

                    b.Property<int>("VelocidadBase")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Pokemons", t =>
                        {
                            t.HasCheckConstraint("CK_Pokemon_AtaqueBase", "[AtaqueBase] >= 1");

                            t.HasCheckConstraint("CK_Pokemon_AtaqueEspecialBase", "[AtaqueEspecialBase] >= 1");

                            t.HasCheckConstraint("CK_Pokemon_DefensaBase", "[DefensaBase] >= 1");

                            t.HasCheckConstraint("CK_Pokemon_DefensaEspecialBase", "[DefensaEspecialBase] >= 1");

                            t.HasCheckConstraint("CK_Pokemon_SaludTotalBase", "[SaludTotalBase] >= 1");

                            t.HasCheckConstraint("CK_Pokemon_VelocidadBase", "[VelocidadBase] >= 1");
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonMovimiento", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "MovimientoId");

                    b.HasIndex("MovimientoId");

                    b.ToTable("PokemonMovimientos");
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonMovimientoPosible", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "MovimientoId");

                    b.HasIndex("MovimientoId");

                    b.ToTable("PokemonMovimientosPosibles");
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonTipo", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "Tipo");

                    b.ToTable("PokemonTipos");
                });

            modelBuilder.Entity("PokemonAPI.Models.MiPokemon", b =>
                {
                    b.HasOne("PokemonAPI.Models.Pokemon", "PokemonBase")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PokemonBase");
                });

            modelBuilder.Entity("PokemonAPI.Models.MiPokemonMovimiento", b =>
                {
                    b.HasOne("PokemonAPI.Models.MiPokemon", "MiPokemon")
                        .WithMany("Movimientos")
                        .HasForeignKey("MiPokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Models.Movimiento", "Movimiento")
                        .WithMany("MisPokemonsQueLoTienen")
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MiPokemon");

                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonMovimiento", b =>
                {
                    b.HasOne("PokemonAPI.Models.Movimiento", "Movimiento")
                        .WithMany("PokemonsQueLoTienen")
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Models.Pokemon", "Pokemon")
                        .WithMany("Movimientos")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimiento");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonMovimientoPosible", b =>
                {
                    b.HasOne("PokemonAPI.Models.Movimiento", "Movimiento")
                        .WithMany("PokemonsQuePuedenAprenderlo")
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Models.Pokemon", "Pokemon")
                        .WithMany("MovimientosPosibles")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimiento");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonTipo", b =>
                {
                    b.HasOne("PokemonAPI.Models.Pokemon", "Pokemon")
                        .WithMany("Tipos")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonAPI.Models.MiPokemon", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("PokemonAPI.Models.Movimiento", b =>
                {
                    b.Navigation("MisPokemonsQueLoTienen");

                    b.Navigation("PokemonsQueLoTienen");

                    b.Navigation("PokemonsQuePuedenAprenderlo");
                });

            modelBuilder.Entity("PokemonAPI.Models.Pokemon", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("MovimientosPosibles");

                    b.Navigation("Tipos");
                });
#pragma warning restore 612, 618
        }
    }
}
